### ISSUE TITLE
iOS not containing content in grid cells with an overflow:auto

### ISSUE THREAD

**Issue by martinduo** [rachelandrew/gridbugs#11]
In a single column layout, iOS does not contain content in grid cells with an overflow:auto property. This bug is present in Safari, Chrome, and Firefox browsers running in iOS on an iPad. This PEN demonstrates the bug.

https://codepen.io/martinduo/pen/GvOWqX

Run this PEN in any browser on an iPad and you’ll see the first and third grid areas rendered showing all 17 rows of the element’s content. This is not the expected result.

Run this PEN in any other browser (that supports CSS Grid Layout) on any other device and you’ll see the first and third grid areas rendered showing 6 rows of content in a scrollable window. This is the expected layout.

**Comment by rachelandrew** [comment]
Is this the same issue as #10?

Are you able to reduce it down further, otherwise it might be a while before I get chance. Also, detail of precise browser/OS versions is helpful.

**Comment by martinduo** [comment]
Yes issue #10 and #11 are the same. Sorry, I was confused and didn't think
my first "Submit" was done, since the draft was still shown.

I am resubmitting with reduced grid: one column, one row, and versions.

**Comment by martinduo** [comment]
A reduced demo has been entered on a later issue
