### ISSUE TITLE
do you remove bugs?

### ISSUE THREAD

**Issue by SerkanSipahi** [rachelandrew/gridbugs#17]
hi, thank your for the buglist :) my question: do you remove bugs that are resolved, respectively fixed?

**Comment by rachelandrew** [comment]
If they were no longer an issue to anyone, but that would essentially mean no-one was using that browser.

**Comment by SerkanSipahi** [comment]
ok, but it will be good when its tags as e.g. -> resolved in "Chrome 65" !

**Comment by rachelandrew** [comment]
as you can see, I have detailed which version it applies to.
