### ISSUE TITLE
Fixed positioning in grid container is calculated wrongly in Safari

### ISSUE THREAD

**Issue by yatil** [rachelandrew/gridbugs#20]
CodePen: https://codepen.io/yatil/pen/WZpKvE

The black test box should be fixed to the bottom right of the screen. In Safari, `bottom` is calculated to `-1275px`, right is calculated to `846px` although both are set to 0 in the CSS:

![screen shot 2017-09-27 at 13 14 54](https://user-images.githubusercontent.com/58862/30910692-14c7884c-a386-11e7-857b-4351751f5ec8.png)

It works as expected in Firefox and Chrome.

**Comment by rachelandrew** [comment]
I can't reproduce this. What version of Safari are you using? In both 11 and TP 40 it is 0.

Maybe I am not understand the issue. I load your example and inspect the span, selecting computed styles. The values for bottom and right are both 0px.

**Comment by yatil** [comment]
Seems to be working here, too. Weird.
