### ISSUE TITLE
Unexpected result if wrapped

### ISSUE THREAD

**Issue by jimmerioles** [rachelandrew/gridbugs#23]
Hi, I'm not quite sure where this issue falls but while i was checking out css grid i noticed it skips the 1st cell when wrapped in a div container.

https://codepen.io/jimmerioles/pen/qNdGvJ

Browser used:
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by rachelandrew** [comment]
You have included Bootstrap.

I would suggest trying out Grid without all of Bootstrap included. You might get more reliable results.

**Comment by jimmerioles** [comment]
Oh my bad.
