### ISSUE TITLE
Input, fieldset bugs in Chrome

### ISSUE THREAD

**Issue by keithjgrant** [rachelandrew/gridbugs#4]
There are two bugs in Chrome that are particularly annoying, relating to forms:

1. If an input or textarea is a grid-item, it collapses to a width of 0 as soon as the user enters some text (OS X) — https://bugs.chromium.org/p/chromium/issues/detail?id=727076

2. Some elements, such a fieldset and button cannot be a grid container — https://bugs.chromium.org/p/chromium/issues/detail?id=375693

**Comment by rachelandrew** [comment]
Thanks - added as [#10](https://github.com/rachelandrew/gridbugs#10-some-html-elements-cant-be-grid-containers) and [#11](https://github.com/rachelandrew/gridbugs#11-a-textarea-that-is-a-grid-item-collapses-to-zero-width)
